
GET http://localhost:3000/products/999

### 

GET http://localhost:3000/categories

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Queso",
    "description": "Queso freso",
    "price": 17.00,
    "stock": 5,
    "category_id": 6
}

###

POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Prueba",
    "description": "Clase añadida para probar peticiones"
}

###

PUT http://localhost:3000/products/5
Content-Type: application/json

{
    "name": "Queso",
    "description": "Queso fresco",
    "price": 17.00,
    "stock": 5,
    "category_id": 2
}

###
DELETE http://localhost:3000/products/7

###

DELETE http://localhost:3000/categories/6


